# Generated by Django 2.1.2 on 2018-11-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20181105_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(related_name='folowed_by', to='profiles.Profile'),
        ),
    ]
