# Generated by Django 2.1.2 on 2018-11-06 07:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, height_field=100, null=True, upload_to='photos/%Y/%m/%d/', width_field=100)),
                ('description', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=None, null=True, size=None)),
                ('time_to_read', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('time_updated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'ordering': ('time_created', 'time_updated'),
            },
        ),
    ]
