# Generated by Django 2.1.2 on 2018-11-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='author',
            new_name='reporter',
        ),
    ]
