# Generated by Django 2.1.2 on 2018-11-21 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20181121_0415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slug',
            new_name='slug_name',
        ),
    ]
