# Generated by Django 2.1.2 on 2018-11-15 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_auto_20181114_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikesDislikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likes', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='_article_dislikes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='_article_likes_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likesdislikes',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='articles.Article'),
        ),
        migrations.AddField(
            model_name='likesdislikes',
            name='reader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='likesdislikes',
            unique_together={('article', 'reader')},
        ),
    ]
