# Generated by Django 2.1.2 on 2019-01-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articlestatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlestatistics',
            name='user',
        ),
    ]
