# Generated by Django 2.1.2 on 2018-11-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181121_0657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='slug_name',
            new_name='slug',
        ),
    ]
