# Generated by Django 2.1.2 on 2018-11-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181107_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='average_rating',
            field=models.IntegerField(default=0),
        ),
    ]
