# Generated by Django 2.1.2 on 2018-11-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('parent_comment', models.ForeignKey(db_column='parent_comment', on_delete=django.db.models.deletion.CASCADE, to='articles.Comment')),
            ],
        ),
    ]
