# Generated by Django 2.1.2 on 2018-11-12 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_highlight_highlighted_article_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='highlighter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL),
        ),
    ]
