# Generated by Django 2.1.2 on 2018-11-12 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20181112_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('time_updated',)},
        ),
        migrations.AlterModelOptions(
            name='highlight',
            options={'ordering': ('time_updated',)},
        ),
        migrations.AddField(
            model_name='highlight',
            name='comment_slug',
            field=models.SlugField(default='comment', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='highlight',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
