# Generated by Django 2.1.2 on 2018-12-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20181213_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='average_rating',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
