# Generated by Django 2.1.2 on 2018-11-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20181112_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='comment_slug',
        ),
    ]
