# Generated by Django 2.1.2 on 2018-11-14 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_commenthistory'),
        ('articles', '0011_remove_highlight_comment_slug'),
    ]

    operations = [
    ]
